#tabs are forbiden in YAML file
version: '3'

services:
  nginx:
    build: ./requirements/nginx/
    container_name: my_nginx
    env_file:
      - .env
    restart: always
    ports:
      - 443:443
    # volumes:
    #   - /home/ubuntu/rstudio_docker/nginx.conf:/etc/nginx/nginx.conf
    #   - /home/ubuntu/ssl:/ssl/

  # wordpress:
    # build: ./requirements/wordpress/
    # container_name: my_wordpress
    # restart: always
    # ports:
      # - 9000:9000
    # env_file:
      # - .env

    
  # mariadb:
  #   build: ./requirements/mariadb/
  #   container_name: my_mariadb
  #   restart: always
      # env_file:
        # - .env
  #   ports:
  #     - 3306:3306

  #volumes makes for persistant databases
  #Vos volumes seront disponibles dans le dossier /home/login/data de la machine hôte utilisant Docker. Bien entendu, remplacez le "login" par le vôtre.